# Generated by Django 5.0.3 on 2024-03-24 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
    ]
