# Generated by Django 5.0.3 on 2024-03-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20240324_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='d', max_length=20),
            preserve_default=False,
        ),
    ]
