# Generated by Django 5.0.3 on 2024-03-24 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_user_phone'),
    ]

    operations = [
    ]
