# Generated by Django 5.0.3 on 2024-03-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_mainservice_field_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainservice',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
