# Generated by Django 5.0.3 on 2024-04-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_requestedservices_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedservices',
            name='status',
            field=models.CharField(default='معلق', max_length=100, null=True),
        ),
    ]
