# Generated by Django 5.0.3 on 2024-04-16 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_requestedservices_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('requestedServices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.requestedservices')),
            ],
        ),
    ]
