# Generated by Django 5.0.3 on 2024-04-16 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='comment',
        ),
    ]
